-- APLICADA 18-08-2026 (registrada como 20260818111533).
-- Port de Mantenimiento al esqueleto (decisión de Luis, 18-08-2026): a
-- diferencia de Compras/PyG/Ratios, aquí los datos SÍ se mudan a Hostelero.
-- Una sola tabla: el parte, con sus fotos dentro (jsonb de dataURLs, como la
-- app original — sin bucket). El esquema calca el original a propósito
-- (fecha en texto incluida) para que el HTML portado cambie lo mínimo;
-- se añade cuenta_id porque esta casa es multi-tenant. Los 38 partes se
-- copiaron con scripts/migrar-mantenimiento.mjs conservando los id.
--
-- Escrituras: el panel (/mantenimiento) escribe como authenticated con la
-- RLS de abajo; el front público (/parte) escribe por /api/publico/parte con
-- service key que valida y pone la cuenta — anon NO tiene política a
-- propósito: la clave publicable no puede tocar esta tabla.

create table mant_partes (
  id bigint generated by default as identity primary key,
  cuenta_id uuid not null references cuentas(id),
  responsable text,
  centro text,
  tipo text,
  fecha text,
  urgencia text,
  descripcion text,
  estado text default 'Pendiente',
  asignado text default '',
  medios jsonb default '[]'::jsonb,
  ts bigint,
  created_at timestamptz default now()
);

alter table mant_partes enable row level security;

create policy mant_partes_select on mant_partes
  for select to authenticated
  using (cuenta_id = cuenta_actual() or es_operador());

create policy mant_partes_insert on mant_partes
  for insert to authenticated
  with check (cuenta_id = cuenta_actual() or es_operador());

-- El panel cambia estado y asignado; no hay política de DELETE porque la app
-- nunca borra un parte (el histórico es parte del valor).
create policy mant_partes_update on mant_partes
  for update to authenticated
  using (cuenta_id = cuenta_actual() or es_operador())
  with check (cuenta_id = cuenta_actual() or es_operador());

create index mant_partes_cuenta_ts on mant_partes (cuenta_id, ts desc);
