/**
 * Textos del widget público y de las páginas por token, en español, inglés, catalán, francés y
 * alemán (plan §2.3). El idioma sale de ?lang= o del navegador (ver detectarIdioma en lib-widget.ts).
 * Los mensajes (email/SMS) solo tienen plantillas es/en: para ca/fr/de el RPC elige la plantilla
 * de reserva (ver nota para el integrador en el informe de la pieza).
 */
export type Lang = "es" | "en" | "ca" | "fr" | "de";

export const LANGS: Lang[] = ["es", "en", "ca", "fr", "de"];

export const esLang = (v: unknown): v is Lang => typeof v === "string" && (LANGS as string[]).includes(v);

/** Nombre de cada idioma en su propia lengua (selector de idioma de los mensajes). */
export const NOMBRE_IDIOMA: Record<Lang, string> = { es: "Español", en: "English", ca: "Català", fr: "Français", de: "Deutsch" };

const ES = {
  marca: "Reservas",
  pasos: ["Encontrar", "Hora", "Datos", "Confirmación"],
  pasosAria: "Pasos",
  idiomaAria: "Idioma",
  pers: "pers.",
  porPersona: "pers.",
  // Paso 1
  dondeReservar: "¿Dónde quieres reservar?",
  eligeRestaurante: "Elige uno de nuestros restaurantes.",
  cargando: "Cargando…",
  comensales: "Comensales",
  mas: "Más",
  dia: "Día",
  verHoras: "Ver horas disponibles",
  buscando: "Buscando mesa…",
  yaTienesReserva: "¿Ya tienes una reserva? Usa el enlace de tu email de confirmación para consultarla, modificarla o cancelarla.",
  cambiarRestaurante: "Cambiar restaurante",
  cerradoDia: "Cerrado",
  diaCompleto: "Ese día está completo para este número de comensales. Puedes apuntarte a la lista de espera en el paso siguiente.",
  // Calendario
  calendario: "Calendario",
  mesAnterior: "Mes anterior",
  mesSiguiente: "Mes siguiente",
  calCompletoTitulo: "Completo: solo lista de espera",
  calDisponible: "Disponible",
  calCompleto: "Completo",
  calCerrado: "Cerrado",
  calError: "No hemos podido cargar la disponibilidad del mes.",
  reintentar: "Reintentar",
  // Paso 2
  eligeHora: "Elige la hora",
  cambiarBusqueda: "Cambiar día o comensales",
  zona: "Zona preferida",
  cualquierZona: "Cualquier zona",
  experiencia: "Experiencia o menú",
  sinExperiencia: "Solo mesa",
  pocasPlazas: "pocas plazas",
  turnoCompleto: "Turno completo",
  turnoCerrado: "Turno cerrado",
  esperaTurno: "Apuntarme a la lista de espera de este turno",
  continuar: "Continuar",
  diaCerrado: "Ese día el restaurante está cerrado. Prueba otra fecha.",
  sinHueco: "No queda mesa online para ese día y ese número de comensales.",
  buscandoOtros: "Buscando mesa en el resto de restaurantes del grupo…",
  siHayEn: "Ese mismo día sí tenemos mesa en:",
  diasCercanos: "Días cercanos con mesa:",
  horasDisponibles: (n: number) => `${n} hora${n === 1 ? "" : "s"} disponible${n === 1 ? "" : "s"}`,
  listaEspera: "Apuntarme a la lista de espera",
  probarOtroDia: "Probar otro día",
  grupoGrande: (pax: number, max: number) => `Para ${pax} personas (más de ${max}) preferimos organizarlo contigo.`,
  grupoSinCupo: "Para esa fecha necesitamos hablarlo contigo.",
  llamanos: "Llámanos al",
  solicitarGrupo: "Solicitar como grupo",
  horaPreferida: "Hora preferida",
  cualquierHora: "Cualquier hora",
  solicitudInfo: "Te confirmaremos la disponibilidad por teléfono o email lo antes posible.",
  garantiaInfo: (imp: string) => `Esta reserva requiere una tarjeta como garantía (${imp}). No se cobra nada salvo que no te presentes o canceles fuera de plazo.`,
  prepagoInfo: (imp: string) => `Esta reserva se abona por adelantado (${imp}). Pasarás al pago seguro al confirmar.`,
  politicaInfo: (h: number) => `Cancelación gratuita hasta ${h} h antes.`,
  // Paso 3
  tusDatos: "Tus datos",
  cambiarHora: "Cambiar hora",
  nombre: "Nombre",
  apellidos: "Apellidos",
  telefono: "Teléfono móvil",
  prefijo: "Prefijo",
  email: "Email",
  idioma: "Idioma",
  comentario: "Comentarios (opcional)",
  comentarioPh: "Trona, carrito, celebración…",
  alergias: "¿Alguna alergia o intolerancia?",
  alergiasPh: "Indícanos cuáles",
  si: "Sí",
  no: "No",
  codigoPromo: "¿Tienes un código promocional?",
  codigo: "Código",
  recomendadoPor: "Reserva recomendada por",
  marketing: "Quiero recibir noticias y ofertas por email.",
  condiciones: "He leído y acepto las",
  condicionesLink: "condiciones de reserva y la política de privacidad",
  rgpdInfo:
    "Responsable: Bonita Menorca S.L. Usamos tus datos para gestionar la reserva y avisarte de ella; solo te enviaremos novedades si marcas la casilla. Las alergias que nos indiques se usan únicamente para preparar tu servicio. Puedes ejercer tus derechos de acceso, rectificación, supresión y oposición como se explica en la",
  rgpdLink: "información de privacidad",
  confirmarReserva: "Confirmar reserva",
  enviarSolicitud: "Enviar solicitud",
  continuarPago: "Continuar al pago",
  reservando: "Reservando…",
  obligatorio: "Obligatorio",
  // Paso 4
  reservaConfirmada: "Reserva confirmada",
  reservaRecibida: "Reserva recibida",
  solicitudRecibida: "Solicitud recibida",
  pendienteRestaurante: "El restaurante la confirmará en breve.",
  localizador: "Localizador",
  hora: "Hora",
  aNombreDe: "A nombre de",
  anadirCalendario: "Añadir al calendario",
  compartirWhatsApp: "Compartir por WhatsApp",
  comoLlegar: "Cómo llegar",
  gestionarReserva: "Ver o modificar mi reserva",
  guardaEnlace: "Te hemos enviado la confirmación por email con el enlace para modificar o cancelar. Si no puedes venir, cancela con antelación: otra persona ocupará tu mesa.",
  otraReserva: "Hacer otra reserva",
  redirigiendoPago: "Te llevamos al pago seguro…",
  irAlPago: "Ir al pago",
  // Invitar a los acompañantes
  invitar: "Invita a tus acompañantes",
  invitarSub: (n: number) => `Les enviamos un email con el día, la hora y la dirección (hasta ${n} ${n === 1 ? "persona" : "personas"}).`,
  invitarEmailPh: "email del acompañante",
  invitarOtro: "Añadir otro email",
  invitarMensaje: "Mensaje (opcional)",
  invitarMensajePh: "¡Nos vemos allí!",
  invitarEnviar: "Enviar invitaciones",
  invitadoOk: (n: number) => (n === 1 ? "Invitación enviada." : `Invitaciones enviadas a ${n} personas.`),
  quitar: "Quitar",
  // Lista de espera
  listaEsperaTitulo: "Lista de espera",
  listaEsperaSub: "Si se libera una mesa ese día, te avisaremos por email.",
  turnoPreferido: "Turno preferido",
  cualquierTurno: "Cualquier turno",
  apuntarme: "Apuntarme",
  apuntado: "Apuntado",
  apuntadoMsg: (rest: string, fecha: string, pax: number) => `Estás en la lista de espera de ${rest} para el ${fecha} (${pax} personas). Si se libera una mesa, te avisaremos.`,
  volver: "Volver",
  volverInicio: "Volver al inicio",
  // Gestión (/reserva/token)
  tuReserva: "Tu reserva",
  estado: "Estado",
  reconfirmar: "Confirmar que vendré",
  reconfirmada: "¡Gracias! Reserva reconfirmada.",
  reconfirmadaPendiente: "Gracias, hemos anotado que vendrás. El restaurante todavía tiene que confirmar la reserva.",
  modificar: "Modificar",
  cancelarReserva: "Cancelar reserva",
  motivoCancelacion: "Motivo (opcional)",
  motivoPh: "Nos ayuda a mejorar",
  avisoCargo: (imp: string, h: number) => `Estás dentro del plazo de ${h} h de la política de cancelación: se aplicará el cargo de ${imp}.`,
  avisoPlazo: (h: number) => `Estás dentro del plazo de ${h} h de la política de cancelación.`,
  confirmarCancelacion: "Sí, cancelar la reserva",
  mantener: "No, mantener",
  canceladaOk: "Reserva cancelada. ¡Te esperamos en otra ocasión!",
  canceladaYa: "Esta reserva está cancelada.",
  reservaPasada: "Esta reserva ya ha pasado.",
  modificarTitulo: "Modificar la reserva",
  guardarCambios: "Guardar cambios",
  modificadaOk: "Reserva modificada.",
  grupoModificar: "Para ese número de comensales tenemos que organizarlo contigo.",
  sinCambios: "No has cambiado nada.",
  pagarAhora: "Introducir tarjeta / pagar",
  pagoPendiente: "Falta la tarjeta o el pago para asegurar la reserva.",
  prepagoEtq: "Prepago",
  garantiaEtq: "Garantía",
  contacto: "Contacto",
  politica: "Política de cancelación",
  valorar: "Valorar la visita",
  noEncontrada: "No encontramos esta reserva",
  noEncontradaSub: "El enlace no es válido o ha caducado. Si necesitas ayuda, contacta con el restaurante.",
  mesas: "Mesa",
  // Valoración
  valorarTitulo: "¿Qué tal fue?",
  valorarSub: (rest: string) => `Cuéntanos cómo fue tu visita a ${rest}. Son 30 segundos.`,
  comida: "La comida",
  atencion: "La atención",
  entorno: "El entorno",
  nps: "¿Nos recomendarías a un amigo?",
  npsNo: "Nada probable",
  npsSi: "Muy probable",
  comentarioValoracion: "¿Algo más que quieras contarnos?",
  enviarValoracion: "Enviar valoración",
  graciasValoracion: "¡Gracias por tu valoración!",
  dejarResena: "Dejar una reseña en Google",
  resenaInvita: "Si te apetece, nos ayuda mucho que lo cuentes en Google.",
  yaValorada: "Ya nos diste tu opinión sobre esta visita. ¡Gracias!",
  noValorable: "Esta reserva todavía no se puede valorar.",
  estados: {
    pendiente: "Pendiente de confirmar",
    confirmada: "Confirmada",
    reconfirmada: "Reconfirmada",
    llegada: "En el restaurante",
    sentada: "En mesa",
    postre: "En mesa",
    cuenta: "En mesa",
    terminada: "Completada",
    no_show: "No presentado",
    cancelada: "Cancelada",
    a_revisar: "Confirmada",
    tarjeta_pendiente: "Pendiente de tarjeta",
    lista_espera: "En lista de espera",
  } as Record<string, string>,
  errores: {
    LOCAL_NO_DISPONIBLE: "Este restaurante no admite reservas online ahora mismo. Llámanos y te atendemos.",
    TELEFONO_INVALIDO: "Revisa el teléfono: necesitamos al menos 9 dígitos.",
    EMAIL_INVALIDO: "Revisa el email: no parece correcto.",
    NOMBRE_REQUERIDO: "Dinos tu nombre para completar la reserva.",
    CONDICIONES_REQUERIDAS: "Tienes que aceptar las condiciones de reserva.",
    PAX_INVALIDO: "El número de comensales no es válido.",
    FECHA_FUERA_DE_RANGO: "Esa fecha queda fuera del calendario de reservas online.",
    HORA_FUERA_DE_TURNO: "Esa hora ya no está disponible. Elige otra.",
    GRUPO_GRANDE: "Para grupos grandes, llámanos y lo organizamos contigo.",
    ANTELACION_INSUFICIENTE: "Esa hora está demasiado cerca. Elige otra o llámanos.",
    SIN_DISPONIBILIDAD: "Justo se ha ocupado esa hora. Elige otra, por favor.",
    CERRADO: "Ese día el restaurante está cerrado.",
    ZONA_INVALIDA: "Esa zona no está disponible.",
    EXPERIENCIA_NO_DISPONIBLE: "Esa experiencia no está disponible para ese día o ese número de personas.",
    CODIGO_INVALIDO: "El código promocional no es válido o ha caducado.",
    DATOS_INVALIDOS: "Revisa los datos: hay algún campo demasiado largo.",
    NO_ENCONTRADA: "No encontramos ninguna reserva con ese enlace.",
    NO_CANCELABLE: "Esta reserva ya no se puede cancelar online. Llámanos y lo vemos.",
    NO_CONFIRMABLE: "Esta reserva no se puede reconfirmar en su estado actual.",
    NO_MODIFICABLE: "Esta reserva ya no se puede modificar online. Llámanos y lo vemos.",
    PAX_PREPAGO: "Con el prepago hecho no se pueden añadir comensales online. Llámanos.",
    REQUIERE_TARJETA: "Para ese número de comensales hace falta garantía con tarjeta. Llámanos y lo gestionamos.",
    VALORACION_INVALIDA: "Puntúa los tres apartados para enviar la valoración.",
    YA_VALORADA: "Esta visita ya está valorada.",
    NO_VALORABLE: "Esta reserva todavía no se puede valorar.",
    NO_INVITABLE: "Ya no se pueden enviar invitaciones para esta reserva.",
    LIMITE_INVITACIONES: "Ya has invitado a todos los acompañantes de esta reserva.",
    SIN_ENVIO: "No hemos podido enviar las invitaciones. Inténtalo más tarde.",
    DEMASIADAS_PETICIONES: "Demasiados intentos seguidos. Espera un momento y vuelve a probar.",
    config_pendiente: "El sistema de reservas no está disponible ahora mismo. Llámanos.",
    datos: "Faltan datos o no son correctos.",
    consulta: "No hemos podido completar la operación. Inténtalo de nuevo.",
    RED: "No hay conexión. Comprueba tu red e inténtalo de nuevo.",
  } as Record<string, string>,
};

type Dic = typeof ES;

const EN: Dic = {
  marca: "Reservations",
  pasos: ["Find", "Time", "Details", "Confirmation"],
  pasosAria: "Steps",
  idiomaAria: "Language",
  pers: "guests",
  porPersona: "guest",
  dondeReservar: "Where would you like to book?",
  eligeRestaurante: "Choose one of our restaurants.",
  cargando: "Loading…",
  comensales: "Guests",
  mas: "More",
  dia: "Date",
  verHoras: "See available times",
  buscando: "Looking for a table…",
  yaTienesReserva: "Already have a booking? Use the link in your confirmation email to view, change or cancel it.",
  cambiarRestaurante: "Change restaurant",
  cerradoDia: "Closed",
  diaCompleto: "That day is fully booked for this party size. You can join the waiting list in the next step.",
  calendario: "Calendar",
  mesAnterior: "Previous month",
  mesSiguiente: "Next month",
  calCompletoTitulo: "Fully booked: waiting list only",
  calDisponible: "Available",
  calCompleto: "Full",
  calCerrado: "Closed",
  calError: "We couldn't load availability for this month.",
  reintentar: "Try again",
  eligeHora: "Pick a time",
  cambiarBusqueda: "Change date or guests",
  zona: "Preferred area",
  cualquierZona: "Any area",
  experiencia: "Experience or menu",
  sinExperiencia: "Table only",
  pocasPlazas: "few left",
  turnoCompleto: "Fully booked",
  turnoCerrado: "Closed",
  esperaTurno: "Join the waiting list for this service",
  continuar: "Continue",
  diaCerrado: "The restaurant is closed that day. Please try another date.",
  sinHueco: "No online tables left for that date and party size.",
  buscandoOtros: "Checking the other restaurants in the group…",
  siHayEn: "That same day we do have a table at:",
  diasCercanos: "Nearby days with tables:",
  horasDisponibles: (n: number) => `${n} time${n === 1 ? "" : "s"} available`,
  listaEspera: "Join the waiting list",
  probarOtroDia: "Try another day",
  grupoGrande: (pax: number, max: number) => `For ${pax} guests (more than ${max}) we'd rather arrange it with you.`,
  grupoSinCupo: "For that date we need to talk it through with you.",
  llamanos: "Call us on",
  solicitarGrupo: "Request as a group",
  horaPreferida: "Preferred time",
  cualquierHora: "Any time",
  solicitudInfo: "We'll confirm availability by phone or email as soon as possible.",
  garantiaInfo: (imp: string) => `This booking requires a card guarantee (${imp}). Nothing is charged unless you don't show up or cancel late.`,
  prepagoInfo: (imp: string) => `This booking is paid in advance (${imp}). You'll go to secure payment after confirming.`,
  politicaInfo: (h: number) => `Free cancellation up to ${h} h before.`,
  tusDatos: "Your details",
  cambiarHora: "Change time",
  nombre: "First name",
  apellidos: "Last name",
  telefono: "Mobile phone",
  prefijo: "Code",
  email: "Email",
  idioma: "Language",
  comentario: "Comments (optional)",
  comentarioPh: "High chair, pushchair, celebration…",
  alergias: "Any allergies or intolerances?",
  alergiasPh: "Tell us which",
  si: "Yes",
  no: "No",
  codigoPromo: "Have a promo code?",
  codigo: "Code",
  recomendadoPor: "Booking recommended by",
  marketing: "I'd like to receive news and offers by email.",
  condiciones: "I have read and accept the",
  condicionesLink: "booking terms and privacy policy",
  rgpdInfo:
    "Data controller: Bonita Menorca S.L. We use your details to manage your booking and keep you informed about it; we'll only send you news if you tick the box. Any allergies you tell us about are used solely to prepare your meal. You can exercise your rights of access, rectification, erasure and objection as explained in our",
  rgpdLink: "privacy information",
  confirmarReserva: "Confirm booking",
  enviarSolicitud: "Send request",
  continuarPago: "Continue to payment",
  reservando: "Booking…",
  obligatorio: "Required",
  reservaConfirmada: "Booking confirmed",
  reservaRecibida: "Booking received",
  solicitudRecibida: "Request received",
  pendienteRestaurante: "The restaurant will confirm it shortly.",
  localizador: "Booking code",
  hora: "Time",
  aNombreDe: "Name",
  anadirCalendario: "Add to calendar",
  compartirWhatsApp: "Share on WhatsApp",
  comoLlegar: "Directions",
  gestionarReserva: "View or change my booking",
  guardaEnlace: "We've emailed you the confirmation with a link to change or cancel. If you can't make it, please cancel in advance so someone else can have the table.",
  otraReserva: "Make another booking",
  redirigiendoPago: "Taking you to secure payment…",
  irAlPago: "Go to payment",
  invitar: "Invite your guests",
  invitarSub: (n: number) => `We'll email them the date, time and address (up to ${n} ${n === 1 ? "person" : "people"}).`,
  invitarEmailPh: "guest's email",
  invitarOtro: "Add another email",
  invitarMensaje: "Message (optional)",
  invitarMensajePh: "See you there!",
  invitarEnviar: "Send invitations",
  invitadoOk: (n: number) => (n === 1 ? "Invitation sent." : `Invitations sent to ${n} people.`),
  quitar: "Remove",
  listaEsperaTitulo: "Waiting list",
  listaEsperaSub: "If a table frees up that day, we'll let you know by email.",
  turnoPreferido: "Preferred service",
  cualquierTurno: "Any service",
  apuntarme: "Join the list",
  apuntado: "You're on the list",
  apuntadoMsg: (rest: string, fecha: string, pax: number) => `You're on the waiting list at ${rest} for ${fecha} (${pax} guests). If a table frees up, we'll let you know.`,
  volver: "Back",
  volverInicio: "Back to start",
  tuReserva: "Your booking",
  estado: "Status",
  reconfirmar: "Confirm I'm coming",
  reconfirmada: "Thank you! Booking reconfirmed.",
  reconfirmadaPendiente: "Thank you, we've noted that you're coming. The restaurant still has to confirm the booking.",
  modificar: "Change",
  cancelarReserva: "Cancel booking",
  motivoCancelacion: "Reason (optional)",
  motivoPh: "It helps us improve",
  avisoCargo: (imp: string, h: number) => `You're within the ${h} h cancellation window: a ${imp} charge will apply.`,
  avisoPlazo: (h: number) => `You're within the ${h} h cancellation window.`,
  confirmarCancelacion: "Yes, cancel the booking",
  mantener: "No, keep it",
  canceladaOk: "Booking cancelled. We hope to see you another time!",
  canceladaYa: "This booking is cancelled.",
  reservaPasada: "This booking has already taken place.",
  modificarTitulo: "Change the booking",
  guardarCambios: "Save changes",
  modificadaOk: "Booking updated.",
  grupoModificar: "For that party size we need to arrange it with you.",
  sinCambios: "Nothing changed.",
  pagarAhora: "Add card / pay",
  pagoPendiente: "A card or payment is still needed to secure the booking.",
  prepagoEtq: "Prepaid",
  garantiaEtq: "Guarantee",
  contacto: "Contact",
  politica: "Cancellation policy",
  valorar: "Rate your visit",
  noEncontrada: "We can't find this booking",
  noEncontradaSub: "The link isn't valid or has expired. If you need help, please contact the restaurant.",
  mesas: "Table",
  valorarTitulo: "How was it?",
  valorarSub: (rest: string) => `Tell us about your visit to ${rest}. It takes 30 seconds.`,
  comida: "The food",
  atencion: "The service",
  entorno: "The setting",
  nps: "Would you recommend us to a friend?",
  npsNo: "Not likely",
  npsSi: "Very likely",
  comentarioValoracion: "Anything else you'd like to tell us?",
  enviarValoracion: "Send rating",
  graciasValoracion: "Thank you for your feedback!",
  dejarResena: "Leave a Google review",
  resenaInvita: "If you fancy it, a Google review helps us a lot.",
  yaValorada: "You've already rated this visit. Thank you!",
  noValorable: "This booking can't be rated yet.",
  estados: {
    pendiente: "Pending confirmation",
    confirmada: "Confirmed",
    reconfirmada: "Reconfirmed",
    llegada: "At the restaurant",
    sentada: "Seated",
    postre: "Seated",
    cuenta: "Seated",
    terminada: "Completed",
    no_show: "No-show",
    cancelada: "Cancelled",
    a_revisar: "Confirmed",
    tarjeta_pendiente: "Card pending",
    lista_espera: "On the waiting list",
  },
  errores: {
    LOCAL_NO_DISPONIBLE: "This restaurant isn't taking online bookings right now. Please call us.",
    TELEFONO_INVALIDO: "Check the phone number: we need at least 9 digits.",
    EMAIL_INVALIDO: "Check the email: it doesn't look right.",
    NOMBRE_REQUERIDO: "Please tell us your name to complete the booking.",
    CONDICIONES_REQUERIDAS: "You need to accept the booking terms.",
    PAX_INVALIDO: "The number of guests isn't valid.",
    FECHA_FUERA_DE_RANGO: "That date is outside the online booking calendar.",
    HORA_FUERA_DE_TURNO: "That time is no longer available. Please pick another.",
    GRUPO_GRANDE: "For large groups, please call us and we'll arrange it.",
    ANTELACION_INSUFICIENTE: "That time is too soon. Pick another or call us.",
    SIN_DISPONIBILIDAD: "That time has just been taken. Please pick another.",
    CERRADO: "The restaurant is closed that day.",
    ZONA_INVALIDA: "That area isn't available.",
    EXPERIENCIA_NO_DISPONIBLE: "That experience isn't available for that date or party size.",
    CODIGO_INVALIDO: "The promo code isn't valid or has expired.",
    DATOS_INVALIDOS: "Check your details: a field is too long.",
    NO_ENCONTRADA: "We can't find a booking for that link.",
    NO_CANCELABLE: "This booking can no longer be cancelled online. Please call us.",
    NO_CONFIRMABLE: "This booking can't be reconfirmed in its current state.",
    NO_MODIFICABLE: "This booking can no longer be changed online. Please call us.",
    PAX_PREPAGO: "Once prepaid, guests can't be added online. Please call us.",
    REQUIERE_TARJETA: "That party size needs a card guarantee. Please call us and we'll sort it.",
    VALORACION_INVALIDA: "Rate all three sections to send your feedback.",
    YA_VALORADA: "This visit has already been rated.",
    NO_VALORABLE: "This booking can't be rated yet.",
    NO_INVITABLE: "Invitations can no longer be sent for this booking.",
    LIMITE_INVITACIONES: "You've already invited all the guests on this booking.",
    SIN_ENVIO: "We couldn't send the invitations. Please try again later.",
    DEMASIADAS_PETICIONES: "Too many attempts in a row. Wait a moment and try again.",
    config_pendiente: "The booking system isn't available right now. Please call us.",
    datos: "Some details are missing or incorrect.",
    consulta: "We couldn't complete that. Please try again.",
    RED: "No connection. Check your network and try again.",
  },
};

const CA: Dic = {
  marca: "Reserves",
  pasos: ["Trobar", "Hora", "Dades", "Confirmació"],
  pasosAria: "Passos",
  idiomaAria: "Idioma",
  pers: "pers.",
  porPersona: "pers.",
  dondeReservar: "On vols reservar?",
  eligeRestaurante: "Tria un dels nostres restaurants.",
  cargando: "Carregant…",
  comensales: "Comensals",
  mas: "Més",
  dia: "Dia",
  verHoras: "Veure hores disponibles",
  buscando: "Cercant taula…",
  yaTienesReserva: "Ja tens una reserva? Fes servir l'enllaç del correu de confirmació per consultar-la, modificar-la o cancel·lar-la.",
  cambiarRestaurante: "Canviar de restaurant",
  cerradoDia: "Tancat",
  diaCompleto: "Aquest dia és complet per a aquest nombre de comensals. Et pots apuntar a la llista d'espera al pas següent.",
  calendario: "Calendari",
  mesAnterior: "Mes anterior",
  mesSiguiente: "Mes següent",
  calCompletoTitulo: "Complet: només llista d'espera",
  calDisponible: "Disponible",
  calCompleto: "Complet",
  calCerrado: "Tancat",
  calError: "No hem pogut carregar la disponibilitat del mes.",
  reintentar: "Tornar-ho a provar",
  eligeHora: "Tria l'hora",
  cambiarBusqueda: "Canviar dia o comensals",
  zona: "Zona preferida",
  cualquierZona: "Qualsevol zona",
  experiencia: "Experiència o menú",
  sinExperiencia: "Només taula",
  pocasPlazas: "poques places",
  turnoCompleto: "Torn complet",
  turnoCerrado: "Torn tancat",
  esperaTurno: "Apuntar-me a la llista d'espera d'aquest torn",
  continuar: "Continuar",
  diaCerrado: "Aquest dia el restaurant és tancat. Prova una altra data.",
  sinHueco: "No queda taula en línia per a aquest dia i aquest nombre de comensals.",
  buscandoOtros: "Cercant taula a la resta de restaurants del grup…",
  siHayEn: "Aquell mateix dia sí que tenim taula a:",
  diasCercanos: "Dies propers amb taula:",
  horasDisponibles: (n: number) => `${n} ${n === 1 ? "hora disponible" : "hores disponibles"}`,
  listaEspera: "Apuntar-me a la llista d'espera",
  probarOtroDia: "Provar un altre dia",
  grupoGrande: (pax: number, max: number) => `Per a ${pax} persones (més de ${max}) preferim organitzar-ho amb tu.`,
  grupoSinCupo: "Per a aquesta data ho hem de parlar amb tu.",
  llamanos: "Truca'ns al",
  solicitarGrupo: "Sol·licitar com a grup",
  horaPreferida: "Hora preferida",
  cualquierHora: "Qualsevol hora",
  solicitudInfo: "Et confirmarem la disponibilitat per telèfon o correu tan aviat com puguem.",
  garantiaInfo: (imp: string) => `Aquesta reserva requereix una targeta com a garantia (${imp}). No es cobra res llevat que no et presentis o cancel·lis fora de termini.`,
  prepagoInfo: (imp: string) => `Aquesta reserva es paga per avançat (${imp}). Passaràs al pagament segur en confirmar.`,
  politicaInfo: (h: number) => `Cancel·lació gratuïta fins a ${h} h abans.`,
  tusDatos: "Les teves dades",
  cambiarHora: "Canviar l'hora",
  nombre: "Nom",
  apellidos: "Cognoms",
  telefono: "Telèfon mòbil",
  prefijo: "Prefix",
  email: "Correu electrònic",
  idioma: "Idioma",
  comentario: "Comentaris (opcional)",
  comentarioPh: "Trona, cotxet, celebració…",
  alergias: "Alguna al·lèrgia o intolerància?",
  alergiasPh: "Indica'ns quines",
  si: "Sí",
  no: "No",
  codigoPromo: "Tens un codi promocional?",
  codigo: "Codi",
  recomendadoPor: "Reserva recomanada per",
  marketing: "Vull rebre notícies i ofertes per correu electrònic.",
  condiciones: "He llegit i accepto les",
  condicionesLink: "condicions de reserva i la política de privacitat",
  rgpdInfo:
    "Responsable: Bonita Menorca S.L. Fem servir les teves dades per gestionar la reserva i avisar-te'n; només t'enviarem novetats si marques la casella. Les al·lèrgies que ens indiquis s'utilitzen únicament per preparar el teu servei. Pots exercir els drets d'accés, rectificació, supressió i oposició tal com s'explica a la",
  rgpdLink: "informació de privacitat",
  confirmarReserva: "Confirmar la reserva",
  enviarSolicitud: "Enviar la sol·licitud",
  continuarPago: "Continuar al pagament",
  reservando: "Reservant…",
  obligatorio: "Obligatori",
  reservaConfirmada: "Reserva confirmada",
  reservaRecibida: "Reserva rebuda",
  solicitudRecibida: "Sol·licitud rebuda",
  pendienteRestaurante: "El restaurant la confirmarà aviat.",
  localizador: "Localitzador",
  hora: "Hora",
  aNombreDe: "A nom de",
  anadirCalendario: "Afegir al calendari",
  compartirWhatsApp: "Compartir per WhatsApp",
  comoLlegar: "Com arribar-hi",
  gestionarReserva: "Veure o modificar la reserva",
  guardaEnlace: "T'hem enviat la confirmació per correu amb l'enllaç per modificar o cancel·lar. Si no pots venir, cancel·la amb antelació: una altra persona ocuparà la teva taula.",
  otraReserva: "Fer una altra reserva",
  redirigiendoPago: "Et portem al pagament segur…",
  irAlPago: "Anar al pagament",
  invitar: "Convida els teus acompanyants",
  invitarSub: (n: number) => `Els enviem un correu amb el dia, l'hora i l'adreça (fins a ${n} ${n === 1 ? "persona" : "persones"}).`,
  invitarEmailPh: "correu de l'acompanyant",
  invitarOtro: "Afegir un altre correu",
  invitarMensaje: "Missatge (opcional)",
  invitarMensajePh: "Ens hi veiem!",
  invitarEnviar: "Enviar les invitacions",
  invitadoOk: (n: number) => (n === 1 ? "Invitació enviada." : `Invitacions enviades a ${n} persones.`),
  quitar: "Treure",
  listaEsperaTitulo: "Llista d'espera",
  listaEsperaSub: "Si s'allibera una taula aquell dia, t'avisarem per correu.",
  turnoPreferido: "Torn preferit",
  cualquierTurno: "Qualsevol torn",
  apuntarme: "Apuntar-me",
  apuntado: "Apuntat",
  apuntadoMsg: (rest: string, fecha: string, pax: number) => `Ets a la llista d'espera de ${rest} per al ${fecha} (${pax} persones). Si s'allibera una taula, t'avisarem.`,
  volver: "Tornar",
  volverInicio: "Tornar a l'inici",
  tuReserva: "La teva reserva",
  estado: "Estat",
  reconfirmar: "Confirmar que vindré",
  reconfirmada: "Gràcies! Reserva reconfirmada.",
  reconfirmadaPendiente: "Gràcies, hem anotat que vindràs. El restaurant encara ha de confirmar la reserva.",
  modificar: "Modificar",
  cancelarReserva: "Cancel·lar la reserva",
  motivoCancelacion: "Motiu (opcional)",
  motivoPh: "Ens ajuda a millorar",
  avisoCargo: (imp: string, h: number) => `Ets dins del termini de ${h} h de la política de cancel·lació: s'aplicarà el càrrec de ${imp}.`,
  avisoPlazo: (h: number) => `Ets dins del termini de ${h} h de la política de cancel·lació.`,
  confirmarCancelacion: "Sí, cancel·lar la reserva",
  mantener: "No, mantenir-la",
  canceladaOk: "Reserva cancel·lada. T'esperem en una altra ocasió!",
  canceladaYa: "Aquesta reserva està cancel·lada.",
  reservaPasada: "Aquesta reserva ja ha passat.",
  modificarTitulo: "Modificar la reserva",
  guardarCambios: "Desar els canvis",
  modificadaOk: "Reserva modificada.",
  grupoModificar: "Per a aquest nombre de comensals ho hem d'organitzar amb tu.",
  sinCambios: "No has canviat res.",
  pagarAhora: "Introduir targeta / pagar",
  pagoPendiente: "Falta la targeta o el pagament per assegurar la reserva.",
  prepagoEtq: "Prepagament",
  garantiaEtq: "Garantia",
  contacto: "Contacte",
  politica: "Política de cancel·lació",
  valorar: "Valorar la visita",
  noEncontrada: "No trobem aquesta reserva",
  noEncontradaSub: "L'enllaç no és vàlid o ha caducat. Si necessites ajuda, contacta amb el restaurant.",
  mesas: "Taula",
  valorarTitulo: "Què tal va anar?",
  valorarSub: (rest: string) => `Explica'ns com va anar la visita a ${rest}. Són 30 segons.`,
  comida: "El menjar",
  atencion: "L'atenció",
  entorno: "L'entorn",
  nps: "Ens recomanaries a un amic?",
  npsNo: "Gens probable",
  npsSi: "Molt probable",
  comentarioValoracion: "Alguna cosa més que ens vulguis explicar?",
  enviarValoracion: "Enviar la valoració",
  graciasValoracion: "Gràcies per la teva valoració!",
  dejarResena: "Deixar una ressenya a Google",
  resenaInvita: "Si et ve de gust, ens ajuda molt que ho expliquis a Google.",
  yaValorada: "Ja ens vas donar la teva opinió sobre aquesta visita. Gràcies!",
  noValorable: "Aquesta reserva encara no es pot valorar.",
  estados: {
    pendiente: "Pendent de confirmar",
    confirmada: "Confirmada",
    reconfirmada: "Reconfirmada",
    llegada: "Al restaurant",
    sentada: "A taula",
    postre: "A taula",
    cuenta: "A taula",
    terminada: "Completada",
    no_show: "No presentat",
    cancelada: "Cancel·lada",
    a_revisar: "Confirmada",
    tarjeta_pendiente: "Pendent de targeta",
    lista_espera: "En llista d'espera",
  },
  errores: {
    LOCAL_NO_DISPONIBLE: "Aquest restaurant no admet reserves en línia ara mateix. Truca'ns i t'atendrem.",
    TELEFONO_INVALIDO: "Revisa el telèfon: necessitem almenys 9 dígits.",
    EMAIL_INVALIDO: "Revisa el correu: no sembla correcte.",
    NOMBRE_REQUERIDO: "Digues-nos el teu nom per completar la reserva.",
    CONDICIONES_REQUERIDAS: "Has d'acceptar les condicions de reserva.",
    PAX_INVALIDO: "El nombre de comensals no és vàlid.",
    FECHA_FUERA_DE_RANGO: "Aquesta data queda fora del calendari de reserves en línia.",
    HORA_FUERA_DE_TURNO: "Aquesta hora ja no està disponible. Tria'n una altra.",
    GRUPO_GRANDE: "Per a grups grans, truca'ns i ho organitzem amb tu.",
    ANTELACION_INSUFICIENTE: "Aquesta hora és massa propera. Tria'n una altra o truca'ns.",
    SIN_DISPONIBILIDAD: "Aquesta hora s'acaba d'ocupar. Tria'n una altra, si us plau.",
    CERRADO: "Aquest dia el restaurant és tancat.",
    ZONA_INVALIDA: "Aquesta zona no està disponible.",
    EXPERIENCIA_NO_DISPONIBLE: "Aquesta experiència no està disponible per a aquest dia o aquest nombre de persones.",
    CODIGO_INVALIDO: "El codi promocional no és vàlid o ha caducat.",
    DATOS_INVALIDOS: "Revisa les dades: hi ha algun camp massa llarg.",
    NO_ENCONTRADA: "No trobem cap reserva amb aquest enllaç.",
    NO_CANCELABLE: "Aquesta reserva ja no es pot cancel·lar en línia. Truca'ns i ho mirem.",
    NO_CONFIRMABLE: "Aquesta reserva no es pot reconfirmar en el seu estat actual.",
    NO_MODIFICABLE: "Aquesta reserva ja no es pot modificar en línia. Truca'ns i ho mirem.",
    PAX_PREPAGO: "Amb el prepagament fet no es poden afegir comensals en línia. Truca'ns.",
    REQUIERE_TARJETA: "Per a aquest nombre de comensals cal garantia amb targeta. Truca'ns i ho gestionem.",
    VALORACION_INVALIDA: "Puntua els tres apartats per enviar la valoració.",
    YA_VALORADA: "Aquesta visita ja està valorada.",
    NO_VALORABLE: "Aquesta reserva encara no es pot valorar.",
    NO_INVITABLE: "Ja no es poden enviar invitacions per a aquesta reserva.",
    LIMITE_INVITACIONES: "Ja has convidat tots els acompanyants d'aquesta reserva.",
    SIN_ENVIO: "No hem pogut enviar les invitacions. Torna-ho a provar més tard.",
    DEMASIADAS_PETICIONES: "Massa intents seguits. Espera un moment i torna-ho a provar.",
    config_pendiente: "El sistema de reserves no està disponible ara mateix. Truca'ns.",
    datos: "Falten dades o no són correctes.",
    consulta: "No hem pogut completar l'operació. Torna-ho a provar.",
    RED: "No hi ha connexió. Comprova la xarxa i torna-ho a provar.",
  },
};

const FR: Dic = {
  marca: "Réservations",
  pasos: ["Trouver", "Heure", "Coordonnées", "Confirmation"],
  pasosAria: "Étapes",
  idiomaAria: "Langue",
  pers: "pers.",
  porPersona: "pers.",
  dondeReservar: "Où souhaitez-vous réserver ?",
  eligeRestaurante: "Choisissez l'un de nos restaurants.",
  cargando: "Chargement…",
  comensales: "Convives",
  mas: "Plus",
  dia: "Date",
  verHoras: "Voir les horaires disponibles",
  buscando: "Recherche d'une table…",
  yaTienesReserva: "Vous avez déjà une réservation ? Utilisez le lien de votre e-mail de confirmation pour la consulter, la modifier ou l'annuler.",
  cambiarRestaurante: "Changer de restaurant",
  cerradoDia: "Fermé",
  diaCompleto: "Ce jour est complet pour ce nombre de convives. Vous pourrez vous inscrire sur la liste d'attente à l'étape suivante.",
  calendario: "Calendrier",
  mesAnterior: "Mois précédent",
  mesSiguiente: "Mois suivant",
  calCompletoTitulo: "Complet : liste d'attente uniquement",
  calDisponible: "Disponible",
  calCompleto: "Complet",
  calCerrado: "Fermé",
  calError: "Impossible de charger les disponibilités du mois.",
  reintentar: "Réessayer",
  eligeHora: "Choisissez l'heure",
  cambiarBusqueda: "Changer la date ou le nombre de convives",
  zona: "Zone préférée",
  cualquierZona: "Indifférent",
  experiencia: "Expérience ou menu",
  sinExperiencia: "Table seule",
  pocasPlazas: "peu de places",
  turnoCompleto: "Service complet",
  turnoCerrado: "Service fermé",
  esperaTurno: "M'inscrire sur la liste d'attente de ce service",
  continuar: "Continuer",
  diaCerrado: "Le restaurant est fermé ce jour-là. Essayez une autre date.",
  sinHueco: "Plus de table en ligne pour cette date et ce nombre de convives.",
  buscandoOtros: "Recherche dans les autres restaurants du groupe…",
  siHayEn: "Ce même jour, nous avons une table à :",
  diasCercanos: "Jours proches avec des tables :",
  horasDisponibles: (n: number) => `${n} horaire${n === 1 ? "" : "s"} disponible${n === 1 ? "" : "s"}`,
  listaEspera: "M'inscrire sur la liste d'attente",
  probarOtroDia: "Essayer un autre jour",
  grupoGrande: (pax: number, max: number) => `Pour ${pax} personnes (plus de ${max}), nous préférons l'organiser avec vous.`,
  grupoSinCupo: "Pour cette date, nous devons en parler avec vous.",
  llamanos: "Appelez-nous au",
  solicitarGrupo: "Demander pour un groupe",
  horaPreferida: "Heure souhaitée",
  cualquierHora: "Indifférent",
  solicitudInfo: "Nous vous confirmerons la disponibilité par téléphone ou par e-mail dès que possible.",
  garantiaInfo: (imp: string) => `Cette réservation nécessite une carte en garantie (${imp}). Rien n'est débité sauf en cas d'absence ou d'annulation tardive.`,
  prepagoInfo: (imp: string) => `Cette réservation se règle à l'avance (${imp}). Vous passerez au paiement sécurisé après confirmation.`,
  politicaInfo: (h: number) => `Annulation gratuite jusqu'à ${h} h avant.`,
  tusDatos: "Vos coordonnées",
  cambiarHora: "Changer l'heure",
  nombre: "Prénom",
  apellidos: "Nom",
  telefono: "Téléphone portable",
  prefijo: "Indicatif",
  email: "E-mail",
  idioma: "Langue",
  comentario: "Commentaires (facultatif)",
  comentarioPh: "Chaise haute, poussette, anniversaire…",
  alergias: "Des allergies ou intolérances ?",
  alergiasPh: "Indiquez-nous lesquelles",
  si: "Oui",
  no: "Non",
  codigoPromo: "Vous avez un code promo ?",
  codigo: "Code",
  recomendadoPor: "Réservation recommandée par",
  marketing: "Je souhaite recevoir des nouvelles et des offres par e-mail.",
  condiciones: "J'ai lu et j'accepte les",
  condicionesLink: "conditions de réservation et la politique de confidentialité",
  rgpdInfo:
    "Responsable du traitement : Bonita Menorca S.L. Nous utilisons vos données pour gérer votre réservation et vous en informer ; nous ne vous enverrons des nouvelles que si vous cochez la case. Les allergies indiquées servent uniquement à préparer votre repas. Vous pouvez exercer vos droits d'accès, de rectification, d'effacement et d'opposition comme expliqué dans les",
  rgpdLink: "informations sur la confidentialité",
  confirmarReserva: "Confirmer la réservation",
  enviarSolicitud: "Envoyer la demande",
  continuarPago: "Continuer vers le paiement",
  reservando: "Réservation en cours…",
  obligatorio: "Obligatoire",
  reservaConfirmada: "Réservation confirmée",
  reservaRecibida: "Réservation reçue",
  solicitudRecibida: "Demande reçue",
  pendienteRestaurante: "Le restaurant la confirmera sous peu.",
  localizador: "Code de réservation",
  hora: "Heure",
  aNombreDe: "Au nom de",
  anadirCalendario: "Ajouter au calendrier",
  compartirWhatsApp: "Partager sur WhatsApp",
  comoLlegar: "Itinéraire",
  gestionarReserva: "Voir ou modifier ma réservation",
  guardaEnlace: "Nous vous avons envoyé la confirmation par e-mail avec le lien pour modifier ou annuler. Si vous ne pouvez pas venir, annulez à l'avance : quelqu'un d'autre pourra profiter de la table.",
  otraReserva: "Faire une autre réservation",
  redirigiendoPago: "Redirection vers le paiement sécurisé…",
  irAlPago: "Aller au paiement",
  invitar: "Invitez vos convives",
  invitarSub: (n: number) => `Nous leur envoyons un e-mail avec la date, l'heure et l'adresse (jusqu'à ${n} ${n === 1 ? "personne" : "personnes"}).`,
  invitarEmailPh: "e-mail du convive",
  invitarOtro: "Ajouter un autre e-mail",
  invitarMensaje: "Message (facultatif)",
  invitarMensajePh: "On se retrouve là-bas !",
  invitarEnviar: "Envoyer les invitations",
  invitadoOk: (n: number) => (n === 1 ? "Invitation envoyée." : `Invitations envoyées à ${n} personnes.`),
  quitar: "Retirer",
  listaEsperaTitulo: "Liste d'attente",
  listaEsperaSub: "Si une table se libère ce jour-là, nous vous préviendrons par e-mail.",
  turnoPreferido: "Service souhaité",
  cualquierTurno: "Indifférent",
  apuntarme: "M'inscrire",
  apuntado: "Inscription enregistrée",
  apuntadoMsg: (rest: string, fecha: string, pax: number) => `Vous êtes sur la liste d'attente de ${rest} pour le ${fecha} (${pax} personnes). Si une table se libère, nous vous préviendrons.`,
  volver: "Retour",
  volverInicio: "Retour à l'accueil",
  tuReserva: "Votre réservation",
  estado: "Statut",
  reconfirmar: "Confirmer ma venue",
  reconfirmada: "Merci ! Réservation reconfirmée.",
  reconfirmadaPendiente: "Merci, nous avons noté votre venue. Le restaurant doit encore confirmer la réservation.",
  modificar: "Modifier",
  cancelarReserva: "Annuler la réservation",
  motivoCancelacion: "Motif (facultatif)",
  motivoPh: "Cela nous aide à nous améliorer",
  avisoCargo: (imp: string, h: number) => `Vous êtes dans le délai de ${h} h de la politique d'annulation : des frais de ${imp} s'appliqueront.`,
  avisoPlazo: (h: number) => `Vous êtes dans le délai de ${h} h de la politique d'annulation.`,
  confirmarCancelacion: "Oui, annuler la réservation",
  mantener: "Non, la conserver",
  canceladaOk: "Réservation annulée. À une prochaine fois !",
  canceladaYa: "Cette réservation est annulée.",
  reservaPasada: "Cette réservation est déjà passée.",
  modificarTitulo: "Modifier la réservation",
  guardarCambios: "Enregistrer",
  modificadaOk: "Réservation modifiée.",
  grupoModificar: "Pour ce nombre de convives, nous devons l'organiser avec vous.",
  sinCambios: "Vous n'avez rien modifié.",
  pagarAhora: "Saisir la carte / payer",
  pagoPendiente: "Il manque la carte ou le paiement pour garantir la réservation.",
  prepagoEtq: "Prépaiement",
  garantiaEtq: "Garantie",
  contacto: "Contact",
  politica: "Politique d'annulation",
  valorar: "Évaluer la visite",
  noEncontrada: "Réservation introuvable",
  noEncontradaSub: "Le lien n'est pas valide ou a expiré. Si vous avez besoin d'aide, contactez le restaurant.",
  mesas: "Table",
  valorarTitulo: "Comment c'était ?",
  valorarSub: (rest: string) => `Racontez-nous votre visite à ${rest}. Cela prend 30 secondes.`,
  comida: "La cuisine",
  atencion: "Le service",
  entorno: "Le cadre",
  nps: "Nous recommanderiez-vous à un ami ?",
  npsNo: "Peu probable",
  npsSi: "Très probable",
  comentarioValoracion: "Autre chose à nous dire ?",
  enviarValoracion: "Envoyer l'évaluation",
  graciasValoracion: "Merci pour votre évaluation !",
  dejarResena: "Laisser un avis sur Google",
  resenaInvita: "Si vous le souhaitez, un avis sur Google nous aide beaucoup.",
  yaValorada: "Vous avez déjà donné votre avis sur cette visite. Merci !",
  noValorable: "Cette réservation ne peut pas encore être évaluée.",
  estados: {
    pendiente: "En attente de confirmation",
    confirmada: "Confirmée",
    reconfirmada: "Reconfirmée",
    llegada: "Au restaurant",
    sentada: "À table",
    postre: "À table",
    cuenta: "À table",
    terminada: "Terminée",
    no_show: "Absent",
    cancelada: "Annulée",
    a_revisar: "Confirmée",
    tarjeta_pendiente: "Carte en attente",
    lista_espera: "Sur liste d'attente",
  },
  errores: {
    LOCAL_NO_DISPONIBLE: "Ce restaurant n'accepte pas de réservations en ligne pour le moment. Appelez-nous.",
    TELEFONO_INVALIDO: "Vérifiez le numéro : il faut au moins 9 chiffres.",
    EMAIL_INVALIDO: "Vérifiez l'e-mail : il ne semble pas correct.",
    NOMBRE_REQUERIDO: "Indiquez votre prénom pour finaliser la réservation.",
    CONDICIONES_REQUERIDAS: "Vous devez accepter les conditions de réservation.",
    PAX_INVALIDO: "Le nombre de convives n'est pas valide.",
    FECHA_FUERA_DE_RANGO: "Cette date est en dehors du calendrier de réservation en ligne.",
    HORA_FUERA_DE_TURNO: "Cette heure n'est plus disponible. Choisissez-en une autre.",
    GRUPO_GRANDE: "Pour les grands groupes, appelez-nous et nous l'organiserons avec vous.",
    ANTELACION_INSUFICIENTE: "Cette heure est trop proche. Choisissez-en une autre ou appelez-nous.",
    SIN_DISPONIBILIDAD: "Cette heure vient d'être prise. Choisissez-en une autre, s'il vous plaît.",
    CERRADO: "Le restaurant est fermé ce jour-là.",
    ZONA_INVALIDA: "Cette zone n'est pas disponible.",
    EXPERIENCIA_NO_DISPONIBLE: "Cette expérience n'est pas disponible pour cette date ou ce nombre de personnes.",
    CODIGO_INVALIDO: "Le code promo n'est pas valide ou a expiré.",
    DATOS_INVALIDOS: "Vérifiez vos données : un champ est trop long.",
    NO_ENCONTRADA: "Aucune réservation ne correspond à ce lien.",
    NO_CANCELABLE: "Cette réservation ne peut plus être annulée en ligne. Appelez-nous.",
    NO_CONFIRMABLE: "Cette réservation ne peut pas être reconfirmée dans son état actuel.",
    NO_MODIFICABLE: "Cette réservation ne peut plus être modifiée en ligne. Appelez-nous.",
    PAX_PREPAGO: "Une fois le prépaiement effectué, on ne peut pas ajouter de convives en ligne. Appelez-nous.",
    REQUIERE_TARJETA: "Pour ce nombre de convives, une garantie par carte est nécessaire. Appelez-nous.",
    VALORACION_INVALIDA: "Notez les trois rubriques pour envoyer l'évaluation.",
    YA_VALORADA: "Cette visite a déjà été évaluée.",
    NO_VALORABLE: "Cette réservation ne peut pas encore être évaluée.",
    NO_INVITABLE: "Il n'est plus possible d'envoyer des invitations pour cette réservation.",
    LIMITE_INVITACIONES: "Vous avez déjà invité tous les convives de cette réservation.",
    SIN_ENVIO: "Impossible d'envoyer les invitations. Réessayez plus tard.",
    DEMASIADAS_PETICIONES: "Trop de tentatives d'affilée. Patientez un instant et réessayez.",
    config_pendiente: "Le système de réservation n'est pas disponible pour le moment. Appelez-nous.",
    datos: "Des informations manquent ou sont incorrectes.",
    consulta: "L'opération n'a pas pu aboutir. Réessayez.",
    RED: "Pas de connexion. Vérifiez votre réseau et réessayez.",
  },
};

const DE: Dic = {
  marca: "Reservierungen",
  pasos: ["Suchen", "Uhrzeit", "Angaben", "Bestätigung"],
  pasosAria: "Schritte",
  idiomaAria: "Sprache",
  pers: "Pers.",
  porPersona: "Pers.",
  dondeReservar: "Wo möchten Sie reservieren?",
  eligeRestaurante: "Wählen Sie eines unserer Restaurants.",
  cargando: "Wird geladen…",
  comensales: "Personen",
  mas: "Mehr",
  dia: "Datum",
  verHoras: "Freie Uhrzeiten anzeigen",
  buscando: "Tisch wird gesucht…",
  yaTienesReserva: "Sie haben bereits reserviert? Über den Link in Ihrer Bestätigungs-E-Mail können Sie die Reservierung ansehen, ändern oder stornieren.",
  cambiarRestaurante: "Restaurant wechseln",
  cerradoDia: "Geschlossen",
  diaCompleto: "Dieser Tag ist für diese Personenzahl ausgebucht. Im nächsten Schritt können Sie sich auf die Warteliste setzen.",
  calendario: "Kalender",
  mesAnterior: "Vorheriger Monat",
  mesSiguiente: "Nächster Monat",
  calCompletoTitulo: "Ausgebucht: nur Warteliste",
  calDisponible: "Frei",
  calCompleto: "Ausgebucht",
  calCerrado: "Geschlossen",
  calError: "Die Verfügbarkeit des Monats konnte nicht geladen werden.",
  reintentar: "Erneut versuchen",
  eligeHora: "Uhrzeit wählen",
  cambiarBusqueda: "Datum oder Personenzahl ändern",
  zona: "Bevorzugter Bereich",
  cualquierZona: "Egal",
  experiencia: "Erlebnis oder Menü",
  sinExperiencia: "Nur Tisch",
  pocasPlazas: "wenige frei",
  turnoCompleto: "Ausgebucht",
  turnoCerrado: "Geschlossen",
  esperaTurno: "Auf die Warteliste für diesen Service",
  continuar: "Weiter",
  diaCerrado: "An diesem Tag ist das Restaurant geschlossen. Bitte wählen Sie ein anderes Datum.",
  sinHueco: "Für dieses Datum und diese Personenzahl ist online kein Tisch mehr frei.",
  buscandoOtros: "Wir suchen in den anderen Restaurants der Gruppe…",
  siHayEn: "Am selben Tag haben wir einen Tisch in:",
  diasCercanos: "Tage in der Nähe mit freien Tischen:",
  horasDisponibles: (n: number) => `${n} ${n === 1 ? "Uhrzeit" : "Uhrzeiten"} frei`,
  listaEspera: "Auf die Warteliste",
  probarOtroDia: "Anderen Tag versuchen",
  grupoGrande: (pax: number, max: number) => `Für ${pax} Personen (mehr als ${max}) organisieren wir das lieber gemeinsam mit Ihnen.`,
  grupoSinCupo: "Für dieses Datum müssen wir das mit Ihnen besprechen.",
  llamanos: "Rufen Sie uns an:",
  solicitarGrupo: "Als Gruppe anfragen",
  horaPreferida: "Gewünschte Uhrzeit",
  cualquierHora: "Egal",
  solicitudInfo: "Wir bestätigen die Verfügbarkeit so bald wie möglich per Telefon oder E-Mail.",
  garantiaInfo: (imp: string) => `Für diese Reservierung ist eine Kreditkarte als Garantie nötig (${imp}). Es wird nichts belastet, außer Sie erscheinen nicht oder stornieren zu spät.`,
  prepagoInfo: (imp: string) => `Diese Reservierung wird im Voraus bezahlt (${imp}). Nach der Bestätigung geht es zur sicheren Zahlung.`,
  politicaInfo: (h: number) => `Kostenlose Stornierung bis ${h} Std. vorher.`,
  tusDatos: "Ihre Angaben",
  cambiarHora: "Uhrzeit ändern",
  nombre: "Vorname",
  apellidos: "Nachname",
  telefono: "Mobiltelefon",
  prefijo: "Vorwahl",
  email: "E-Mail",
  idioma: "Sprache",
  comentario: "Anmerkungen (optional)",
  comentarioPh: "Kinderstuhl, Kinderwagen, Feier…",
  alergias: "Allergien oder Unverträglichkeiten?",
  alergiasPh: "Bitte nennen Sie sie",
  si: "Ja",
  no: "Nein",
  codigoPromo: "Haben Sie einen Aktionscode?",
  codigo: "Code",
  recomendadoPor: "Reservierung empfohlen von",
  marketing: "Ich möchte Neuigkeiten und Angebote per E-Mail erhalten.",
  condiciones: "Ich habe die",
  condicionesLink: "Reservierungsbedingungen und die Datenschutzerklärung gelesen und akzeptiere sie",
  rgpdInfo:
    "Verantwortlich: Bonita Menorca S.L. Wir verwenden Ihre Daten, um Ihre Reservierung zu verwalten und Sie darüber zu informieren; Neuigkeiten senden wir nur, wenn Sie das Kästchen ankreuzen. Angaben zu Allergien dienen ausschließlich der Zubereitung Ihres Essens. Ihre Rechte auf Auskunft, Berichtigung, Löschung und Widerspruch können Sie wie in den",
  rgpdLink: "Datenschutzhinweisen beschrieben ausüben",
  confirmarReserva: "Reservierung bestätigen",
  enviarSolicitud: "Anfrage senden",
  continuarPago: "Weiter zur Zahlung",
  reservando: "Wird reserviert…",
  obligatorio: "Pflichtfeld",
  reservaConfirmada: "Reservierung bestätigt",
  reservaRecibida: "Reservierung erhalten",
  solicitudRecibida: "Anfrage erhalten",
  pendienteRestaurante: "Das Restaurant bestätigt sie in Kürze.",
  localizador: "Reservierungscode",
  hora: "Uhrzeit",
  aNombreDe: "Auf den Namen",
  anadirCalendario: "Zum Kalender hinzufügen",
  compartirWhatsApp: "Per WhatsApp teilen",
  comoLlegar: "Anfahrt",
  gestionarReserva: "Reservierung ansehen oder ändern",
  guardaEnlace: "Wir haben Ihnen die Bestätigung mit dem Link zum Ändern oder Stornieren per E-Mail geschickt. Wenn Sie nicht kommen können, stornieren Sie bitte rechtzeitig, damit jemand anderes den Tisch bekommt.",
  otraReserva: "Neue Reservierung",
  redirigiendoPago: "Weiterleitung zur sicheren Zahlung…",
  irAlPago: "Zur Zahlung",
  invitar: "Laden Sie Ihre Begleitung ein",
  invitarSub: (n: number) => `Wir senden ihnen eine E-Mail mit Datum, Uhrzeit und Adresse (bis zu ${n} ${n === 1 ? "Person" : "Personen"}).`,
  invitarEmailPh: "E-Mail der Begleitperson",
  invitarOtro: "Weitere E-Mail hinzufügen",
  invitarMensaje: "Nachricht (optional)",
  invitarMensajePh: "Bis dann!",
  invitarEnviar: "Einladungen senden",
  invitadoOk: (n: number) => (n === 1 ? "Einladung gesendet." : `Einladungen an ${n} Personen gesendet.`),
  quitar: "Entfernen",
  listaEsperaTitulo: "Warteliste",
  listaEsperaSub: "Wird an diesem Tag ein Tisch frei, benachrichtigen wir Sie per E-Mail.",
  turnoPreferido: "Gewünschter Service",
  cualquierTurno: "Egal",
  apuntarme: "Eintragen",
  apuntado: "Eingetragen",
  apuntadoMsg: (rest: string, fecha: string, pax: number) => `Sie stehen auf der Warteliste von ${rest} für ${fecha} (${pax} Personen). Wird ein Tisch frei, benachrichtigen wir Sie.`,
  volver: "Zurück",
  volverInicio: "Zum Anfang",
  tuReserva: "Ihre Reservierung",
  estado: "Status",
  reconfirmar: "Ich komme",
  reconfirmada: "Danke! Reservierung bestätigt.",
  reconfirmadaPendiente: "Danke, wir haben notiert, dass Sie kommen. Das Restaurant muss die Reservierung noch bestätigen.",
  modificar: "Ändern",
  cancelarReserva: "Reservierung stornieren",
  motivoCancelacion: "Grund (optional)",
  motivoPh: "Das hilft uns, besser zu werden",
  avisoCargo: (imp: string, h: number) => `Sie liegen innerhalb der ${h}-Stunden-Frist der Stornobedingungen: Es wird eine Gebühr von ${imp} berechnet.`,
  avisoPlazo: (h: number) => `Sie liegen innerhalb der ${h}-Stunden-Frist der Stornobedingungen.`,
  confirmarCancelacion: "Ja, Reservierung stornieren",
  mantener: "Nein, behalten",
  canceladaOk: "Reservierung storniert. Wir freuen uns auf ein anderes Mal!",
  canceladaYa: "Diese Reservierung ist storniert.",
  reservaPasada: "Diese Reservierung liegt bereits in der Vergangenheit.",
  modificarTitulo: "Reservierung ändern",
  guardarCambios: "Änderungen speichern",
  modificadaOk: "Reservierung geändert.",
  grupoModificar: "Für diese Personenzahl müssen wir das mit Ihnen organisieren.",
  sinCambios: "Sie haben nichts geändert.",
  pagarAhora: "Karte eingeben / bezahlen",
  pagoPendiente: "Zur Sicherung der Reservierung fehlt noch die Karte oder die Zahlung.",
  prepagoEtq: "Vorauszahlung",
  garantiaEtq: "Garantie",
  contacto: "Kontakt",
  politica: "Stornobedingungen",
  valorar: "Besuch bewerten",
  noEncontrada: "Reservierung nicht gefunden",
  noEncontradaSub: "Der Link ist ungültig oder abgelaufen. Wenn Sie Hilfe brauchen, wenden Sie sich an das Restaurant.",
  mesas: "Tisch",
  valorarTitulo: "Wie war es?",
  valorarSub: (rest: string) => `Erzählen Sie uns von Ihrem Besuch in ${rest}. Es dauert 30 Sekunden.`,
  comida: "Das Essen",
  atencion: "Der Service",
  entorno: "Das Ambiente",
  nps: "Würden Sie uns einem Freund empfehlen?",
  npsNo: "Unwahrscheinlich",
  npsSi: "Sehr wahrscheinlich",
  comentarioValoracion: "Möchten Sie uns noch etwas sagen?",
  enviarValoracion: "Bewertung senden",
  graciasValoracion: "Vielen Dank für Ihre Bewertung!",
  dejarResena: "Bewertung bei Google schreiben",
  resenaInvita: "Wenn Sie mögen, hilft uns eine Bewertung bei Google sehr.",
  yaValorada: "Sie haben diesen Besuch bereits bewertet. Danke!",
  noValorable: "Diese Reservierung kann noch nicht bewertet werden.",
  estados: {
    pendiente: "Unbestätigt",
    confirmada: "Bestätigt",
    reconfirmada: "Erneut bestätigt",
    llegada: "Im Restaurant",
    sentada: "Am Tisch",
    postre: "Am Tisch",
    cuenta: "Am Tisch",
    terminada: "Abgeschlossen",
    no_show: "Nicht erschienen",
    cancelada: "Storniert",
    a_revisar: "Bestätigt",
    tarjeta_pendiente: "Karte ausstehend",
    lista_espera: "Auf der Warteliste",
  },
  errores: {
    LOCAL_NO_DISPONIBLE: "Dieses Restaurant nimmt gerade keine Online-Reservierungen an. Bitte rufen Sie uns an.",
    TELEFONO_INVALIDO: "Bitte prüfen Sie die Telefonnummer: Wir brauchen mindestens 9 Ziffern.",
    EMAIL_INVALIDO: "Bitte prüfen Sie die E-Mail-Adresse.",
    NOMBRE_REQUERIDO: "Bitte geben Sie Ihren Namen an, um die Reservierung abzuschließen.",
    CONDICIONES_REQUERIDAS: "Bitte akzeptieren Sie die Reservierungsbedingungen.",
    PAX_INVALIDO: "Die Personenzahl ist ungültig.",
    FECHA_FUERA_DE_RANGO: "Dieses Datum liegt außerhalb des Online-Reservierungskalenders.",
    HORA_FUERA_DE_TURNO: "Diese Uhrzeit ist nicht mehr frei. Bitte wählen Sie eine andere.",
    GRUPO_GRANDE: "Für große Gruppen rufen Sie uns bitte an, wir organisieren es gemeinsam.",
    ANTELACION_INSUFICIENTE: "Diese Uhrzeit ist zu kurzfristig. Wählen Sie eine andere oder rufen Sie uns an.",
    SIN_DISPONIBILIDAD: "Diese Uhrzeit wurde gerade vergeben. Bitte wählen Sie eine andere.",
    CERRADO: "An diesem Tag ist das Restaurant geschlossen.",
    ZONA_INVALIDA: "Dieser Bereich ist nicht verfügbar.",
    EXPERIENCIA_NO_DISPONIBLE: "Dieses Erlebnis ist für dieses Datum oder diese Personenzahl nicht verfügbar.",
    CODIGO_INVALIDO: "Der Aktionscode ist ungültig oder abgelaufen.",
    DATOS_INVALIDOS: "Bitte prüfen Sie Ihre Angaben: Ein Feld ist zu lang.",
    NO_ENCONTRADA: "Zu diesem Link gibt es keine Reservierung.",
    NO_CANCELABLE: "Diese Reservierung kann nicht mehr online storniert werden. Bitte rufen Sie uns an.",
    NO_CONFIRMABLE: "Diese Reservierung kann in ihrem aktuellen Status nicht bestätigt werden.",
    NO_MODIFICABLE: "Diese Reservierung kann nicht mehr online geändert werden. Bitte rufen Sie uns an.",
    PAX_PREPAGO: "Nach der Vorauszahlung können online keine Personen hinzugefügt werden. Bitte rufen Sie uns an.",
    REQUIERE_TARJETA: "Für diese Personenzahl ist eine Kartengarantie nötig. Bitte rufen Sie uns an.",
    VALORACION_INVALIDA: "Bitte bewerten Sie alle drei Bereiche.",
    YA_VALORADA: "Dieser Besuch wurde bereits bewertet.",
    NO_VALORABLE: "Diese Reservierung kann noch nicht bewertet werden.",
    NO_INVITABLE: "Für diese Reservierung können keine Einladungen mehr gesendet werden.",
    LIMITE_INVITACIONES: "Sie haben bereits alle Begleitpersonen dieser Reservierung eingeladen.",
    SIN_ENVIO: "Die Einladungen konnten nicht gesendet werden. Bitte versuchen Sie es später erneut.",
    DEMASIADAS_PETICIONES: "Zu viele Versuche hintereinander. Bitte warten Sie einen Moment.",
    config_pendiente: "Das Reservierungssystem ist gerade nicht verfügbar. Bitte rufen Sie uns an.",
    datos: "Angaben fehlen oder sind nicht korrekt.",
    consulta: "Der Vorgang konnte nicht abgeschlossen werden. Bitte versuchen Sie es erneut.",
    RED: "Keine Verbindung. Bitte prüfen Sie Ihr Netzwerk und versuchen Sie es erneut.",
  },
};

export const TEXTOS: Record<Lang, Dic> = { es: ES, en: EN, ca: CA, fr: FR, de: DE };

export function textos(lang: Lang) {
  return TEXTOS[lang] ?? ES;
}
